FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD account-email.jar /opt/account-email/
EXPOSE 8080
WORKDIR /opt/account-email/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "account-email.jar"]
